# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!

target 'KinopoiskApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KinopoiskApp
  
  # Autocomplete
  pod 'R.swift', '~> 5.0.3'
  
  # Reactive
  pod 'RxSwift'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxDataSources', '~> 3.0'
  pod 'RxGesture'
  
  # Autolayout
  pod 'SnapKit', '~> 4.0.0'
  
  # Utilities
  pod 'Kingfisher'

end
